server:
  port: 6002

spring:
  mysql:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password:
  kafka:
    ip: localhost:9092
    customTopic:
      test_topic: test-consume
    consumer:
      auto-offset-reset: earliest
      group-id: sk
  data:
    mongodb:
      uri: mongodb://localhost:27017/quickbi
    # spring.kafka.consumer.auto-offset-reset=earliest

rest:
  api:
    chineseCities: https://search.heweather.com/top?key=7d826aa6040240c5ad96e0f5304b004a&group=cn
